[project]
name = "agentic-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nagesh Sarode", email = "nageshsarode52@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "langchain>=1.0.0",
    "langchain-groq>=0.3.0",
    "python-dotenv>=1.0.0",
    "httpx>=0.28.0",
    "streamlit>=1.62.0",
]

[project.scripts]
agentic-ai = "agentic_ai:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
